version: '2.1'
orbs:
  go: circleci/go@1.12.0
jobs:
  build:
    executor:
      name: go/default
      tag: '1.23.2'
    steps:
      - checkout
      - go/test:
          covermode: atomic
          no_output_timeout: 15m
          race: true
          timeout: 15m
          verbose: true
workflows:
  main:
    jobs:
      - build