name: bailiff

on:
  push:

jobs:
  build:
    uses: ethereum-optimism/factory/.github/workflows/docker-build.yaml@71910a32b9b897d46f8576a42ade344719d2bba9
    with:
      image_name: ${{ github.workflow }}
      context: .
      dockerfile: Dockerfile
      platforms: linux/amd64
      gcp_project_id: ${{ vars.GCP_PROJECT_ID_OPLABS_TOOLS_ARTIFACTS }}
      gcp_registry: us-docker.pkg.dev/oplabs-tools-artifacts/oss
    permissions:
      contents: read
      id-token: write
      attestations: write

